/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The list of currently available songs.
 */
export type ListSongsResponse = Response & {
  songs?: Song[];
  page_token?: string;
  [k: string]: unknown;
};

/**
 * A response that could return error information.
 */
export interface Response {
  command_status?: 0 | 1 | 2 | 3 | 4 | 5;
  error_message?: string;
  error_data?: string;
  [k: string]: unknown;
}
/**
 * A song that can be played by the media player.
 */
export interface Song {
  name?: string;
  description?: string;
  metadata?: {
    [k: string]: string;
  };
  local_path?: string;
  [k: string]: unknown;
}
