/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Playlist of songs that can be played by the media player.
 */
export interface Playlist {
  name?: string;
  description?: string;
  metadata?: {
    [k: string]: string;
  };
  songs?: string[];
  [k: string]: unknown;
}
