/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Toggle the play state. Can optionally set the media player to the absolute "play" or "pause" state.
 */
export interface TogglePlayCommand {
  play_state?: boolean;
  [k: string]: unknown;
}
