/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Response to a play command.
 */
export type TogglePlayResponse = Response & {
  new_play_state?: boolean;
  [k: string]: unknown;
};

/**
 * A response that could return error information.
 */
export interface Response {
  command_status?: 0 | 1 | 2 | 3 | 4 | 5;
  error_message?: string;
  error_data?: string;
  [k: string]: unknown;
}
